# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ComponentSwiftDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CKWrapperDemo
  pod 'ComponentSwift', :path => '../'
  pod 'WrapExisted', :path => './WrapExisted'
  pod 'ComponentKit', :inhibit_warnings => true


end

pre_install do |installer|
  # genereate header file.
  # This is a convenience for developing. Just ignore this. 
  system 'python ../Script/generate_umbrella_header.py'
end
