# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CKWrapperDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CKWrapperDemo
  pod 'CKWrapper', :path => '../'
  pod 'WrapExisted', :path => './WrapExisted'
  pod 'ComponentKit', :inhibit_warnings => true


end
